### ISSUE TITLE
깃 브랜치 전략

### ISSUE THREAD

**Issue by Reading-Snail** [Hexa-24/BACK_END#11]
깃 브랜치 전략에 대한 어느 정도의 합의가 필요해 보입니다.

6명의 팀으로 사이드 프로젝트를 진행할 때 효율적인 브랜치 전략을 선택하는 것은 중요합니다. 아래에 여러 가지 가능한 브랜치 전략을 제시하고, 프로젝트의 규모, 팀의 구성원, 협업 방식 등을 고려하여 선택할 수 있습니다:

### 1. Git Flow:
- **주요 특징**: 기능 개발, 버그 수정, 릴리스 준비 등을 위한 다양한 종류의 브랜치를 사용하는 전략입니다.
- **브랜치 구성**:
  - `main`: 제품으로 출시될 수 있는 안정적인 코드가 유지되는 메인 브랜치
  - `develop`: 다음 릴리스를 위한 개발을 진행하는 브랜치
  - `feature/*`: 새로운 기능을 개발하는 데 사용되는 브랜치
  - `bugfix/*`: 버그를 수정하는 데 사용되는 브랜치
  - `release/*`: 프로덕션 배포를 준비하는 데 사용되는 브랜치
- **장점**: 구조가 명확하고 이해하기 쉽습니다.
- **단점**: 브랜치가 많아질 수 있으며, 팀원들 간의 협업에 복잡성을 초래할 수 있습니다.

### 2. GitHub Flow:
- **주요 특징**: 단순하고 직관적인 브랜치 전략으로, `main` 브랜치에 계속해서 코드를 통합하는 방식입니다.
- **브랜치 구성**:
  - `main`: 항상 배포 가능한 상태를 유지하는 브랜치
  - `feature/*` 또는 `bugfix/*`: 각각의 기능 또는 버그 수정을 위한 브랜치
- **장점**: 단순하고 빠르게 배우고 적용할 수 있습니다.
- **단점**: 대규모 프로젝트에서는 제한적일 수 있습니다.

### 3. Trunk-Based Development:
- **주요 특징**: 간단하고 빠른 개발을 위해 `main` 브랜치에 직접 작업하는 전략입니다.
- **브랜치 구성**:
  - `main`: 모든 개발이 진행되는 브랜치
- **장점**: 브랜치 관리의 복잡성이 없으며, 코드 통합이 빠릅니다.
- **단점**: 특정 기능을 분리해서 개발하기 어려울 수 있으며, 충돌을 해결하기 어려울 수 있습니다.

### 선택 기준:
- 팀의 개발 경험과 선호도
- 프로젝트의 규모와 복잡성
- 배포 주기와 협업 방식
- 프로젝트의 특성과 요구사항

이러한 요소를 고려하여 적절한 브랜치 전략을 선택하세요. 필요에 따라 선택한 전략을 수정하거나 조정할 수도 있습니다.

**Comment by jackie-k** [comment]
개인적으로 gitflow 전략이 익숙해서 gitflow를 사용하는것도 좋을 것 같습니다

**Comment by Reading-Snail** [comment]
그럼 특별히 이견 없으시면 Git Flow 전략으로 브랜치 구조 잡도로 하겠습니다.

프론트앤드 쪽은 제가 개발환경 설정 하는 방법을 몰라 네분이서 상의하셔서 진행해 놓으셔야 될 것 같습니다!
